### ISSUE TITLE
Mineshafts don't spawn with Terraforged

### ISSUE THREAD

**Issue by glarmer** [yungnickyoung/YUNGs-Better-Mineshafts#46] opened 2021-02-20 16:18 UTC
The structures in this mod do not generate with Terraforged worlds, I've contacted the mod author for Terraforged and this is apparently because "The mod that added the structure needs to register their "structure separation settings". These settings tell the chunkgenerator how to space each structure type out - if they're not registered TF can't know how the structure should generate."

The mod author linked me: https://github.com/TerraForged/TerraForged/wiki/Mod:-Structures:-Compatibility
Which demonstrates how to implement the solution to this issue

**Comment by yungnickyoung** [comment] 2021-02-20 21:44
Duplicate of #8

**Closed as completed** 2021-02-20 21:44 UTC
Labels: duplicate
