### ISSUE TITLE
Mineshafts not generating with terraforge

### ISSUE THREAD

**Issue by BentiGorlich** [yungnickyoung/YUNGs-Better-Mineshafts#49] opened 2021-02-26 10:29 UTC
I use terraforge for my world gen and sadly better mineshafts is not working with it. When i use /locate to find a mineshaft it says nothing nearby and in the server log i get
> [TerraForged/]: Structure [bettermineshafts:mineshaft] does not have any generation settings registered for it so it cannot be generated!

MC Version: 1.16.5
Forge Version: 36.0.14
Better Mineshafts Version: 2.0.1
Terraforged Version: 0.2.8

**Comment by ElBrigos** [comment] 2021-02-27 08:10
Hello, i have the same issues, in 1.15.2 it's works, but in 1.16.5 not work

**Comment by zanecek** [comment] 2021-03-03 07:29
How to spawn bettermineshaft (and dungeon_plus, the_conjurer,...) structures with terraforged (1.16.5):
1) Run minecraft
2) Create vanilla world (these structures are generated well)
3) Close vanilla world
4) Create terraforged world (structures remained "in system" and are generated, you can check them in the terraforged setup)

**Comment by BentiGorlich** [comment] 2021-03-04 07:45
And how would I do It on the serverside? Or is there no way of doing that?

**Comment by zanecek** [comment] 2021-03-04 19:09
I don't know. I play single worlds only.

**Comment by yungnickyoung** [comment] 2021-03-06 00:47
Duplicate of #8

**Closed as completed by yungnickyoung** 2021-03-06 00:47 UTC
