### ISSUE TITLE
[1.16.4, latest version] /locate command not working

### ISSUE THREAD

**Issue by MoreKerosine** [yungnickyoung/YUNGs-Better-Mineshafts#31] opened 2020-11-17 14:52 UTC
I was in spectator mode, inside of a mineshaft, but the /locate command would only locate one that tried to generate in the ocean, almost 100 blocks away from where I was. I know ocean mineshafts don't generate, but that doesn't explain why /locate couldn't find the one I was in.

**Comment by yungnickyoung** [comment] 2021-01-19 03:43
Closing because I suspect the issue is that the ocean mineshaft (which doesn't actually generate as you've pointed out) was actually closer than the starting point of the mineshaft  you were in. I haven't been able to recreate this issue at all, nor have I heard of others experiencing it.

**Closed as completed by yungnickyoung** 2021-01-19 03:43 UTC
