### ISSUE TITLE
[1.16] Mineshafts are spawning in an in-dev void dimension mod, can't find a config setting to disable

### ISSUE THREAD

**Issue by aaronhowser1** [yungnickyoung/YUNGs-Better-Mineshafts#42] opened 2021-02-04 12:14 UTC
FTB Schools is basically a mod that has two void dimensions which dynamically generate school buildings in the void as they're needed. It uses the dimension ids `ftbschools:school_day` and `ftbschools:school_night`.

![image](https://user-images.githubusercontent.com/15698722/106891123-e6a7d200-66af-11eb-8284-33251ff2d796.png)
![image](https://user-images.githubusercontent.com/15698722/106891157-f45d5780-66af-11eb-8871-51319cdb128e.png)

Mineshafts are generating in the void around the schools. I couldn't find a config, or a dimension blacklist. The dev for FTB Schools says it's disabling structures:
![image](https://user-images.githubusercontent.com/15698722/106891321-2078d880-66b0-11eb-8dda-71250175e423.png)
Is there a way to blacklist structures from this mod's side?

**Comment by aaronhowser1** [comment] 2021-02-04 12:16
![image](https://user-images.githubusercontent.com/15698722/106891506-646bdd80-66b0-11eb-81d5-c902e004e22d.png)

**Comment by yungnickyoung** [comment] 2021-02-06 07:06
It should only operate on biomes that have vanilla mineshafts. What version are you on?

**Comment by aaronhowser1** [comment] 2021-02-06 07:09
BetterMineshafts-Forge-1.16.4-2.0.1

Does it not check if there's anywhere to actually put them before spawning them? I suppose we could make a custom biome for it, it's using Plains as it is.

**Comment by yungnickyoung** [comment] 2021-02-06 17:53
No, it simply generates supports below it in the event it spawns in the air. I would just make a quick void biome that doesn't have any structure starts.

**Comment by MaxNeedsSnacks** [comment] 2021-02-06 23:08
> No, it simply generates supports below it in the event it spawns in the air. I would just make a quick void biome that doesn't have any structure starts.

Did just that and it works fine ^^
On a related note, though, I feel like there should still be a way to explicitly allow / deny dims in which mineshafts can spawn, or otherwise checking whether spawning them would make sense, like in the case of RFTools custom void dimensions as it **might**(?) still break there as well if the user doesn't explicitly use a biome dimlet that DOESN'T have structure starts

**Comment by yungnickyoung** [comment] 2021-02-07 17:36
If it were 1.12 I would agree with you, but in 1.16 you have complete control over this without any sort of dimension blacklisting thanks to datapacks.

If a biome has a mineshaft structure start, it will spawn a mineshaft. If you don't want mineshafts in that biome, either remove it from the structure starts or use a duplicate of the biome and remove the mineshaft structure start from that duplicate entry.

It's pretty straightforward behavior and is working exactly as intended.

**Closed as completed** 2021-02-17 03:21 UTC
