### ISSUE TITLE
Incompatibility with Atum Dimension world gen

### ISSUE THREAD

**Issue by SouthernPixel** [yungnickyoung/YUNGs-Better-Mineshafts#27] opened 2020-11-11 12:27 UTC
Game crashes when generating a Atum Dimension https://pastebin.com/yA51fn1p

**Comment by SouthernPixel** [comment] 2020-11-11 12:34
Just tried it again but without your better mineshafts and its doing the same thing with your better caves mod as well. Is there any way to make it where it only effects the overworld? I really want to use Atum and your mods

**Comment by yungnickyoung** [comment] 2020-11-11 23:30
Duplicate of #19 ?

**Comment by SouthernPixel** [comment] 2020-11-13 07:02
I dont think I can downgrade to 2.0.17 because dynamic trees atum requires this specific version of atum

**Comment by yungnickyoung** [comment] 2020-11-13 07:33
You need to upgrade to 2.0.19

**Comment by SouthernPixel** [comment] 2020-11-13 12:03
upgrade what? Atum or your mods? I'll try when I wake up.

**Comment by yungnickyoung** [comment] 2020-11-13 20:07
Atum

**Closed as completed by yungnickyoung** 2020-11-13 20:07 UTC
